/** Catalogue definitions for the demo store. Brands are fictional on purpose. */
export interface ProductDef {
  leaf: string;
  brand: string;
  name: string;
  /** 0 = TechNest Retail (electronics) · 1 = Fashion Bazaar · 2 = HomeCraft India */
  seller: 0 | 1 | 2;
  mrp: number;
  off: number;
  gst: number;
  hsn: string;
  blurb: string;
  highlights: string[];
  specs: Array<[string, string]>;
  /** attribute slug → values; variants are the cartesian product */
  axes?: Record<string, string[]>;
  /** per-axis price multipliers by value index, e.g. storage: [0, 0.14] */
  bump?: Record<string, number[]>;
  /** attributes that describe the product but don't create variants */
  attrs?: Record<string, string>;
  tags?: string[];
}

const C3 = ['Black', 'White', 'Navy'];

export const PRODUCTS: ProductDef[] = [
  // ───────── Smartphones
  {
    leaf: 'smartphones',
    brand: 'Nova Mobiles',
    name: 'Nova X12 5G Smartphone',
    seller: 0,
    mrp: 24999,
    off: 28,
    gst: 18,
    hsn: '8517',
    blurb:
      'A fast, dependable 5G phone with a vivid 120 Hz AMOLED display and a 50 MP camera that handles low light with ease.',
    highlights: [
      '6.67" 120 Hz AMOLED display',
      '50 MP OIS main camera',
      '5000 mAh battery with 67 W fast charging',
      'Snapdragon 7-series 5G processor',
    ],
    specs: [
      ['Display', '6.67 inch AMOLED, 120 Hz'],
      ['Processor', 'Octa-core 5G, 2.4 GHz'],
      ['Rear camera', '50 MP + 8 MP ultrawide'],
      ['Front camera', '16 MP'],
      ['Battery', '5000 mAh'],
      ['OS', 'Android 15'],
      ['Warranty', '1 year manufacturer'],
    ],
    axes: { color: ['Midnight', 'Starlight'], storage: ['128 GB', '256 GB'] },
    bump: { storage: [0, 0.14] },
    attrs: { ram: '8 GB' },
    tags: ['5g', 'android', 'amoled'],
  },
  {
    leaf: 'smartphones',
    brand: 'Nova Mobiles',
    name: 'Nova Pro 14 5G Flagship',
    seller: 0,
    mrp: 44999,
    off: 22,
    gst: 18,
    hsn: '8517',
    blurb:
      'Flagship performance with a Leica-style triple camera, LTPO display and all-day battery in a slim aluminium body.',
    highlights: [
      '6.78" LTPO AMOLED, 144 Hz',
      '200 MP periscope telephoto system',
      '100 W wired + 50 W wireless charging',
      'IP68 water resistance',
    ],
    specs: [
      ['Display', '6.78 inch LTPO AMOLED'],
      ['Processor', 'Flagship 4 nm 5G'],
      ['Rear camera', '200 MP + 50 MP + 12 MP'],
      ['Battery', '5400 mAh'],
      ['OS', 'Android 15'],
      ['Warranty', '1 year manufacturer'],
    ],
    axes: { color: ['Black', 'Silver', 'Gold'], storage: ['256 GB', '512 GB'] },
    bump: { storage: [0, 0.16] },
    attrs: { ram: '12 GB' },
    tags: ['flagship', '5g'],
  },
  {
    leaf: 'smartphones',
    brand: 'Orbit Tech',
    name: 'Orbit Lite 5G Smartphone',
    seller: 0,
    mrp: 14999,
    off: 33,
    gst: 18,
    hsn: '8517',
    blurb:
      'Budget 5G that does not feel budget: smooth 90 Hz screen, clean software and a battery that lasts two days.',
    highlights: [
      '6.6" 90 Hz FHD+ display',
      '50 MP dual camera',
      '6000 mAh battery',
      'Dedicated microSD slot',
    ],
    specs: [
      ['Display', '6.6 inch FHD+, 90 Hz'],
      ['Processor', 'Octa-core 5G'],
      ['Battery', '6000 mAh'],
      ['OS', 'Android 14'],
    ],
    axes: { color: ['Blue', 'Green'], storage: ['64 GB', '128 GB'] },
    bump: { storage: [0, 0.1] },
    attrs: { ram: '6 GB' },
  },
  // ───────── Mobile accessories
  {
    leaf: 'mobile-cases',
    brand: 'Voltix',
    name: 'Voltix ShockGuard Armour Case',
    seller: 0,
    mrp: 799,
    off: 55,
    gst: 18,
    hsn: '3926',
    blurb:
      'Military-grade drop protection with raised bezels and precise cut-outs, without the bulk.',
    highlights: [
      'Tested against 3 m drops',
      'Raised camera and screen lip',
      'Wireless-charging friendly',
    ],
    specs: [
      ['Material', 'TPU + polycarbonate'],
      ['Compatibility', 'Nova X12 / Pro 14'],
    ],
    axes: { color: ['Black', 'Blue', 'Red'] },
    attrs: { material: 'Polyester' },
  },
  {
    leaf: 'mobile-cases',
    brand: 'Orbit Tech',
    name: 'Orbit Crystal Clear Case',
    seller: 0,
    mrp: 599,
    off: 50,
    gst: 18,
    hsn: '3926',
    blurb: 'Anti-yellowing crystal clear case that shows off your phone while keeping it safe.',
    highlights: ['Anti-yellowing coating', 'Slim, grippy edges'],
    specs: [['Material', 'Clear TPU']],
    axes: { color: ['White', 'Black'] },
  },
  {
    leaf: 'power-banks',
    brand: 'Voltix',
    name: 'Voltix PowerMax 22.5 W Power Bank',
    seller: 0,
    mrp: 2499,
    off: 40,
    gst: 18,
    hsn: '8507',
    blurb:
      'Fast-charging power bank with dual outputs and a bright LED indicator — keep two devices alive all day.',
    highlights: ['22.5 W fast charging', 'Type-C in/out', 'Smart power management'],
    specs: [
      ['Input', 'Type-C 18 W'],
      ['Output', '22.5 W max'],
      ['Warranty', '12 months'],
    ],
    axes: { capacity: ['10000 mAh', '20000 mAh'], color: ['Black', 'White'] },
    bump: { capacity: [0, 0.55] },
  },
  {
    leaf: 'power-banks',
    brand: 'Orbit Tech',
    name: 'Orbit Slim 10000 mAh Power Bank',
    seller: 0,
    mrp: 1499,
    off: 35,
    gst: 18,
    hsn: '8507',
    blurb: 'Pocket-slim power bank that charges a phone twice over.',
    highlights: ['Credit-card thin', '15 W output', 'Pass-through charging'],
    specs: [
      ['Capacity', '10000 mAh'],
      ['Output', '15 W'],
    ],
    axes: { color: ['Grey', 'Blue'] },
  },
  // ───────── Laptops
  {
    leaf: 'laptops',
    brand: 'Orbit Tech',
    name: 'Orbit Book Air 14 Laptop',
    seller: 0,
    mrp: 64990,
    off: 18,
    gst: 18,
    hsn: '8471',
    blurb:
      'An ultraportable that does not compromise: 1.2 kg, 14" 2.8K display and 15 hours of real-world battery.',
    highlights: [
      '14" 2.8K 90 Hz display',
      '1.2 kg aluminium chassis',
      'Up to 15 h battery',
      'Backlit keyboard + fingerprint reader',
    ],
    specs: [
      ['Processor', '12-core mobile CPU'],
      ['Display', '14 inch 2.8K OLED'],
      ['Graphics', 'Integrated'],
      ['OS', 'Windows 11 Home'],
      ['Warranty', '1 year on-site'],
    ],
    axes: { ram: ['8 GB', '16 GB'], storage: ['256 GB', '512 GB'] },
    bump: { ram: [0, 0.16], storage: [0, 0.1] },
    tags: ['ultrabook'],
  },
  {
    leaf: 'laptops',
    brand: 'Orbit Tech',
    name: 'Orbit Book Pro 16 Creator Laptop',
    seller: 0,
    mrp: 119990,
    off: 15,
    gst: 18,
    hsn: '8471',
    blurb:
      'A workstation for creators with a colour-accurate 16" mini-LED display and a dedicated GPU.',
    highlights: [
      '16" mini-LED, 100% DCI-P3',
      'Dedicated 8 GB GPU',
      'Thunderbolt 4 ports',
      'Vapour-chamber cooling',
    ],
    specs: [
      ['Processor', '14-core high performance CPU'],
      ['Display', '16 inch mini-LED'],
      ['Graphics', '8 GB dedicated'],
      ['OS', 'Windows 11 Pro'],
    ],
    axes: { ram: ['16 GB', '32 GB'], storage: ['512 GB', '1 TB'] },
    bump: { ram: [0, 0.18], storage: [0, 0.14] },
  },
  {
    leaf: 'laptops',
    brand: 'Voltix',
    name: 'Voltix StudentBook 15 Laptop',
    seller: 0,
    mrp: 38990,
    off: 24,
    gst: 18,
    hsn: '8471',
    blurb:
      'Everything a student needs — a light 15.6" laptop with a long-lasting battery and a fast SSD.',
    highlights: ['15.6" FHD anti-glare', 'Numpad keyboard', 'Fast charge: 50% in 30 min'],
    specs: [
      ['Processor', '8-core mobile CPU'],
      ['OS', 'Windows 11 Home'],
    ],
    axes: { storage: ['256 GB', '512 GB'] },
    bump: { storage: [0, 0.12] },
    attrs: { ram: '8 GB' },
  },
  // ───────── Audio
  {
    leaf: 'headphones',
    brand: 'Zenith Audio',
    name: 'Zenith Aura ANC Wireless Headphones',
    seller: 0,
    mrp: 7999,
    off: 62,
    gst: 18,
    hsn: '8518',
    blurb:
      'Hybrid active noise cancellation, 60-hour battery and plush memory-foam cushions for all-day comfort.',
    highlights: [
      'Hybrid ANC up to 40 dB',
      '60 h playtime, 10 min = 5 h',
      'Multipoint Bluetooth 5.3',
      'Companion app with 10-band EQ',
    ],
    specs: [
      ['Driver', '40 mm dynamic'],
      ['Battery', '60 hours'],
      ['Charging', 'USB-C'],
      ['Weight', '250 g'],
    ],
    axes: { color: ['Black', 'White', 'Blue'] },
    attrs: { connectivity: 'Bluetooth 5.3' },
    tags: ['anc', 'wireless'],
  },
  {
    leaf: 'headphones',
    brand: 'Zenith Audio',
    name: 'Zenith Beat Buds TWS Earbuds',
    seller: 0,
    mrp: 2999,
    off: 70,
    gst: 18,
    hsn: '8518',
    blurb:
      'True wireless earbuds with punchy bass, ENC calling and a pocket-friendly charging case.',
    highlights: [
      '13 mm bass drivers',
      'ENC for clear calls',
      '40 h total playtime',
      'IPX5 sweat resistant',
    ],
    specs: [
      ['Bluetooth', '5.3'],
      ['Battery', '40 h with case'],
    ],
    axes: { color: ['Black', 'White'] },
    attrs: { connectivity: 'Bluetooth 5.3' },
    tags: ['tws'],
  },
  {
    leaf: 'headphones',
    brand: 'Voltix',
    name: 'Voltix BassWave Wired Headphones',
    seller: 0,
    mrp: 999,
    off: 50,
    gst: 18,
    hsn: '8518',
    blurb: 'Comfortable wired over-ear headphones with inline mic — no charging required.',
    highlights: ['Inline mic and controls', '1.2 m tangle-free cable'],
    specs: [
      ['Driver', '40 mm'],
      ['Jack', '3.5 mm'],
    ],
    axes: { color: ['Black', 'Red'] },
    attrs: { connectivity: 'Wired' },
  },
  {
    leaf: 'bluetooth-speakers',
    brand: 'Zenith Audio',
    name: 'Zenith Boom 360 Bluetooth Speaker',
    seller: 0,
    mrp: 4999,
    off: 55,
    gst: 18,
    hsn: '8518',
    blurb: '360° sound with deep bass, party lights and a rugged IP67 body that floats.',
    highlights: [
      '360° room-filling sound',
      'IP67 waterproof, floats',
      '24 h playtime',
      'Party-link up to 100 speakers',
    ],
    specs: [
      ['Output', '20 W RMS'],
      ['Battery', '24 hours'],
    ],
    axes: { color: ['Black', 'Blue', 'Red'] },
    attrs: { connectivity: 'Bluetooth 5.3' },
  },
  {
    leaf: 'bluetooth-speakers',
    brand: 'Voltix',
    name: 'Voltix Mini Pebble Speaker',
    seller: 0,
    mrp: 1999,
    off: 50,
    gst: 18,
    hsn: '8518',
    blurb: 'Palm-sized Bluetooth speaker with surprisingly full sound.',
    highlights: ['10 W sound', '12 h playtime', 'Built-in mic'],
    specs: [['Output', '10 W']],
    axes: { color: ['Teal', 'Grey'] },
    attrs: { connectivity: 'Bluetooth 5.3' },
  },
  // ───────── Wearables & TV
  {
    leaf: 'smartwatches',
    brand: 'Orbit Tech',
    name: 'Orbit Pulse Active Smartwatch',
    seller: 0,
    mrp: 5999,
    off: 67,
    gst: 18,
    hsn: '9102',
    blurb: 'Track workouts, sleep and SpO₂ on a bright 1.85" display with Bluetooth calling.',
    highlights: ['1.85" bright display', 'Bluetooth calling', '100+ sports modes', '7-day battery'],
    specs: [
      ['Display', '1.85 inch LCD'],
      ['Water resistance', 'IP68'],
      ['Battery', 'Up to 7 days'],
    ],
    axes: { color: ['Black', 'Silver', 'Pink'] },
  },
  {
    leaf: 'smartwatches',
    brand: 'Nova Mobiles',
    name: 'Nova Watch S2 AMOLED',
    seller: 0,
    mrp: 9999,
    off: 55,
    gst: 18,
    hsn: '9102',
    blurb: 'AMOLED smartwatch with built-in GPS, ECG and a premium stainless-steel case.',
    highlights: ['1.43" AMOLED, always-on', 'Built-in GPS', 'ECG and HRV', 'Stainless steel case'],
    specs: [
      ['Display', '1.43 inch AMOLED'],
      ['GPS', 'Built-in'],
    ],
    axes: { color: ['Black', 'Gold'] },
  },
  {
    leaf: 'televisions',
    brand: 'Orbit Tech',
    name: 'Orbit Vision 4K Smart LED TV',
    seller: 0,
    mrp: 36990,
    off: 40,
    gst: 28,
    hsn: '8528',
    blurb: 'Crisp 4K HDR with a fast Google TV interface, Dolby Audio and a bezel-less design.',
    highlights: [
      '4K Ultra HD HDR10+',
      'Google TV, Chromecast built-in',
      'Dolby Audio 24 W',
      'Game mode (ALLM)',
    ],
    specs: [
      ['Resolution', '3840 x 2160'],
      ['Refresh rate', '60 Hz'],
      ['HDMI', '3 (1 eARC)'],
      ['Warranty', '1 year + 1 year panel'],
    ],
    axes: { 'screen-size': ['43 inch', '50 inch', '55 inch'] },
    bump: { 'screen-size': [0, 0.28, 0.55] },
    tags: ['4k', 'smart-tv'],
  },
  {
    leaf: 'televisions',
    brand: 'Nova Mobiles',
    name: 'Nova QLED Smart TV',
    seller: 0,
    mrp: 64990,
    off: 35,
    gst: 28,
    hsn: '8528',
    blurb: 'Quantum-dot colour and local dimming for cinema-grade contrast in a living room.',
    highlights: ['QLED 4K, 120 Hz', 'Dolby Vision + Atmos', 'Far-field voice assistant'],
    specs: [
      ['Resolution', '3840 x 2160'],
      ['Refresh rate', '120 Hz'],
    ],
    axes: { 'screen-size': ['55 inch', '65 inch'] },
    bump: { 'screen-size': [0, 0.5] },
  },
  // ───────── Men's fashion
  {
    leaf: 'mens-tshirts',
    brand: 'Urban Weave',
    name: 'Urban Weave Classic Crew Neck T-Shirt',
    seller: 1,
    mrp: 899,
    off: 55,
    gst: 5,
    hsn: '6109',
    blurb: 'A wardrobe staple in 180 GSM combed cotton that stays soft wash after wash.',
    highlights: ['180 GSM combed cotton', 'Pre-shrunk, bio-washed', 'Regular fit'],
    specs: [
      ['Fabric', '100% cotton'],
      ['Fit', 'Regular'],
      ['Care', 'Machine wash cold'],
    ],
    axes: { size: ['M', 'L', 'XL'], color: C3 },
    attrs: { material: 'Cotton' },
    tags: ['basics'],
  },
  {
    leaf: 'mens-tshirts',
    brand: 'Urban Weave',
    name: 'Urban Weave Oversized Graphic Tee',
    seller: 1,
    mrp: 1299,
    off: 60,
    gst: 5,
    hsn: '6109',
    blurb: 'Drop-shoulder oversized tee with a soft-touch screen print.',
    highlights: ['240 GSM heavyweight cotton', 'Drop shoulder', 'Water-based print'],
    specs: [
      ['Fabric', '100% cotton'],
      ['Fit', 'Oversized'],
    ],
    axes: { size: ['M', 'L', 'XL'], color: ['Black', 'Beige'] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'mens-tshirts',
    brand: 'Stride Labs',
    name: 'Stride Labs Dry-Fit Training Tee',
    seller: 1,
    mrp: 999,
    off: 50,
    gst: 12,
    hsn: '6109',
    blurb: 'Moisture-wicking, quick-dry tee engineered for runs, gym floors and humid commutes.',
    highlights: ['Quick-dry polyester', 'Reflective logo', 'Anti-odour finish'],
    specs: [['Fabric', 'Recycled polyester']],
    axes: { size: ['M', 'L', 'XL'], color: ['Black', 'Blue', 'Green'] },
    attrs: { material: 'Polyester' },
  },
  {
    leaf: 'mens-shirts',
    brand: 'Urban Weave',
    name: 'Urban Weave Oxford Button-Down Shirt',
    seller: 1,
    mrp: 1999,
    off: 55,
    gst: 12,
    hsn: '6205',
    blurb:
      'The shirt that works from boardroom to brunch — a crisp oxford weave with a soft collar roll.',
    highlights: ['Premium oxford cotton', 'Button-down collar', 'Slim-regular fit'],
    specs: [
      ['Fabric', '100% cotton'],
      ['Fit', 'Slim'],
    ],
    axes: { size: ['M', 'L', 'XL'], color: ['White', 'Blue'] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'mens-shirts',
    brand: 'Urban Weave',
    name: 'Urban Weave Pure Linen Casual Shirt',
    seller: 1,
    mrp: 2499,
    off: 50,
    gst: 12,
    hsn: '6205',
    blurb: 'Breathable pure linen made for Indian summers; relaxed, textured and easy to style.',
    highlights: ['100% European flax linen', 'Relaxed fit', 'Mother-of-pearl buttons'],
    specs: [['Fabric', '100% linen']],
    axes: { size: ['M', 'L', 'XL'], color: ['Beige', 'Olive', 'Navy'] },
    attrs: { material: 'Linen' },
  },
  {
    leaf: 'mens-jeans',
    brand: 'Urban Weave',
    name: 'Urban Weave Slim Fit Stretch Jeans',
    seller: 1,
    mrp: 2999,
    off: 55,
    gst: 12,
    hsn: '6203',
    blurb: 'Comfort-stretch denim with a modern slim taper and a clean mid-rise.',
    highlights: ['2% elastane stretch', 'Mid-rise, slim taper', 'Colour-fast indigo'],
    specs: [['Fabric', '98% cotton, 2% elastane']],
    axes: { size: ['M', 'L', 'XL'], color: ['Blue', 'Black'] },
    attrs: { material: 'Denim' },
  },
  {
    leaf: 'mens-jeans',
    brand: 'Urban Weave',
    name: 'Urban Weave Relaxed Fit Denim',
    seller: 1,
    mrp: 3299,
    off: 45,
    gst: 12,
    hsn: '6203',
    blurb: 'Rigid, weighty denim in a relaxed straight cut that softens with every wear.',
    highlights: ['12 oz rigid denim', 'Straight leg', 'Reinforced stitching'],
    specs: [['Fabric', '100% cotton denim']],
    axes: { size: ['M', 'L', 'XL'] },
    attrs: { material: 'Denim', color: 'Blue' },
  },
  {
    leaf: 'mens-sports-shoes',
    brand: 'Stride Labs',
    name: 'Stride Labs Cloudrunner Running Shoes',
    seller: 1,
    mrp: 4999,
    off: 52,
    gst: 12,
    hsn: '6404',
    blurb: 'Cushioned daily trainer with a responsive foam midsole and breathable engineered mesh.',
    highlights: [
      'Responsive EVA+ foam',
      'Engineered breathable mesh',
      'Rubber outsole with flex grooves',
    ],
    specs: [
      ['Upper', 'Engineered mesh'],
      ['Sole', 'EVA + rubber'],
      ['Drop', '8 mm'],
    ],
    axes: { 'shoe-size': ['7', '8', '9', '10'], color: ['Black', 'Blue'] },
    tags: ['running'],
  },
  {
    leaf: 'mens-sports-shoes',
    brand: 'Stride Labs',
    name: 'Stride Labs Trail Grip Shoes',
    seller: 1,
    mrp: 5999,
    off: 45,
    gst: 12,
    hsn: '6404',
    blurb: 'Aggressive lugs and a rock plate for confident footing on dirt, gravel and wet rock.',
    highlights: ['5 mm multi-directional lugs', 'Rock plate protection', 'Water-repellent upper'],
    specs: [['Upper', 'Ripstop mesh']],
    axes: { 'shoe-size': ['8', '9', '10'], color: ['Olive', 'Black'] },
  },
  {
    leaf: 'mens-sports-shoes',
    brand: 'Boltz Sports',
    name: 'Boltz Court Pro Badminton Shoes',
    seller: 1,
    mrp: 3999,
    off: 50,
    gst: 12,
    hsn: '6404',
    blurb: 'Non-marking gum sole and lateral support for quick court movement.',
    highlights: ['Non-marking gum rubber sole', 'Lateral stability cage', 'Shock-absorbing heel'],
    specs: [['Sole', 'Gum rubber']],
    axes: { 'shoe-size': ['7', '8', '9', '10'], color: ['White', 'Blue'] },
  },
  // ───────── Women's fashion
  {
    leaf: 'sarees',
    brand: 'Kaveri Looms',
    name: 'Kaveri Looms Kanjivaram Pure Silk Saree',
    seller: 1,
    mrp: 14999,
    off: 35,
    gst: 5,
    hsn: '5007',
    blurb:
      'Handwoven Kanjivaram silk with a rich zari border and a traditional temple motif pallu.',
    highlights: [
      'Handwoven pure mulberry silk',
      'Real zari border',
      'Includes unstitched blouse piece',
    ],
    specs: [
      ['Fabric', 'Pure silk'],
      ['Length', '6.3 m with blouse piece'],
      ['Care', 'Dry clean only'],
    ],
    axes: { color: ['Maroon', 'Green', 'Gold'] },
    attrs: { material: 'Silk' },
    tags: ['wedding', 'handloom'],
  },
  {
    leaf: 'sarees',
    brand: 'Kaveri Looms',
    name: 'Kaveri Looms Handloom Cotton Saree',
    seller: 1,
    mrp: 2499,
    off: 40,
    gst: 5,
    hsn: '5208',
    blurb: 'Light, breathable handloom cotton with a contrast border for everyday elegance.',
    highlights: ['Handloom cotton', 'Soft, breathable drape', 'Contrast woven border'],
    specs: [
      ['Fabric', 'Cotton'],
      ['Length', '5.5 m + blouse piece'],
    ],
    axes: { color: ['Teal', 'Pink', 'Yellow'] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'sarees',
    brand: 'Mehfil Ethnics',
    name: 'Mehfil Ethnics Georgette Party Saree',
    seller: 1,
    mrp: 3999,
    off: 55,
    gst: 5,
    hsn: '5407',
    blurb: 'Flowy georgette with sequin work — made for evenings that call for a little sparkle.',
    highlights: ['Lightweight georgette', 'Sequin embellishment', 'Ready-to-wear blouse piece'],
    specs: [['Fabric', 'Georgette']],
    axes: { color: ['Maroon', 'Teal'] },
    attrs: { material: 'Polyester' },
  },
  {
    leaf: 'kurtas',
    brand: 'Mehfil Ethnics',
    name: 'Mehfil Ethnics Printed Straight Kurta',
    seller: 1,
    mrp: 1499,
    off: 55,
    gst: 5,
    hsn: '6104',
    blurb: 'Block-print straight kurta in breathable cotton, finished with delicate piping.',
    highlights: ['Cotton block print', 'Mandarin collar', 'Side slits for easy movement'],
    specs: [
      ['Fabric', 'Cotton'],
      ['Length', 'Knee length'],
    ],
    axes: { size: ['S', 'M', 'L', 'XL'], color: ['Teal', 'Pink'] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'kurtas',
    brand: 'Mehfil Ethnics',
    name: 'Mehfil Ethnics Embroidered Anarkali Kurta',
    seller: 1,
    mrp: 3299,
    off: 50,
    gst: 5,
    hsn: '6104',
    blurb: 'A flared Anarkali with intricate thread embroidery on the yoke — festive but wearable.',
    highlights: ['Thread embroidery', 'Flared silhouette', 'Cotton-silk blend'],
    specs: [['Fabric', 'Cotton silk']],
    axes: { size: ['S', 'M', 'L'], color: ['Maroon', 'Navy'] },
    attrs: { material: 'Silk' },
  },
  {
    leaf: 'kurtas',
    brand: 'Mehfil Ethnics',
    name: 'Mehfil Ethnics Cotton Kurta With Palazzo Set',
    seller: 1,
    mrp: 2499,
    off: 48,
    gst: 5,
    hsn: '6104',
    blurb: 'A coordinated kurta and palazzo set that is effortless from office to dinner.',
    highlights: ['Kurta + palazzo set', 'Soft cotton', 'Elasticated waist'],
    specs: [['Set', 'Kurta, palazzo']],
    axes: { size: ['S', 'M', 'L', 'XL'], color: ['Yellow', 'Green'] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'dresses',
    brand: 'Urban Weave',
    name: 'Urban Weave Floral Midi Dress',
    seller: 1,
    mrp: 2299,
    off: 55,
    gst: 12,
    hsn: '6204',
    blurb: 'A swishy floral midi with a flattering waist tie and flutter sleeves.',
    highlights: ['Lightweight viscose crepe', 'Tie waist', 'Side pockets'],
    specs: [['Fabric', 'Viscose crepe']],
    axes: { size: ['S', 'M', 'L'], color: ['Pink', 'Blue'] },
  },
  {
    leaf: 'dresses',
    brand: 'Urban Weave',
    name: 'Urban Weave Wrap Dress',
    seller: 1,
    mrp: 2799,
    off: 50,
    gst: 12,
    hsn: '6204',
    blurb: 'A versatile wrap dress that drapes beautifully and goes anywhere.',
    highlights: ['V-neck wrap', 'Adjustable fit', 'Fluid drape'],
    specs: [['Fabric', 'Polyester georgette']],
    axes: { size: ['S', 'M', 'L'], color: ['Maroon', 'Green'] },
  },
  {
    leaf: 'handbags',
    brand: 'Cedar & Co',
    name: 'Cedar & Co Vegan Leather Tote Bag',
    seller: 1,
    mrp: 3499,
    off: 57,
    gst: 18,
    hsn: '4202',
    blurb: 'A structured tote that fits a 14" laptop, with a zip-top and plenty of pockets.',
    highlights: ['Fits up to 14" laptop', 'Magnetic + zip closure', 'Detachable pouch'],
    specs: [
      ['Material', 'Vegan leather'],
      ['Dimensions', '38 x 28 x 12 cm'],
    ],
    axes: { color: ['Brown', 'Black', 'Beige'] },
    attrs: { material: 'Leather' },
  },
  {
    leaf: 'handbags',
    brand: 'Cedar & Co',
    name: 'Cedar & Co Crossbody Sling Bag',
    seller: 1,
    mrp: 1999,
    off: 50,
    gst: 18,
    hsn: '4202',
    blurb: 'Compact crossbody with an adjustable strap — hands-free style for the day.',
    highlights: ['Adjustable strap', 'Two zip compartments'],
    specs: [['Material', 'Vegan leather']],
    axes: { color: ['Maroon', 'Black'] },
    attrs: { material: 'Leather' },
  },
  // ───────── Home & kitchen
  {
    leaf: 'sofas',
    brand: 'Aarav Home',
    name: 'Aarav Home Nordic 3-Seater Fabric Sofa',
    seller: 2,
    mrp: 42999,
    off: 38,
    gst: 18,
    hsn: '9401',
    blurb:
      'Scandinavian lines, solid-wood legs and high-resilience foam — a living-room centrepiece.',
    highlights: [
      'High-density foam seating',
      'Solid sheesham wood legs',
      'Removable cushion covers',
      '2-year frame warranty',
    ],
    specs: [
      ['Seating', '3 seater'],
      ['Dimensions', '200 x 85 x 82 cm'],
      ['Assembly', 'Basic, tools included'],
    ],
    axes: { color: ['Grey', 'Beige', 'Teal'] },
    attrs: { material: 'Wood' },
    tags: ['furniture'],
  },
  {
    leaf: 'sofas',
    brand: 'Aarav Home',
    name: 'Aarav Home Recliner Armchair',
    seller: 2,
    mrp: 21999,
    off: 30,
    gst: 18,
    hsn: '9401',
    blurb: 'A manual recliner with plush padding and a smooth glide mechanism.',
    highlights: ['Smooth reclining mechanism', 'Padded headrest', 'Easy-clean upholstery'],
    specs: [['Seating', '1 seater']],
    axes: { color: ['Brown', 'Grey'] },
    attrs: { material: 'Leather' },
  },
  {
    leaf: 'cookware',
    brand: 'Aarav Home',
    name: 'Aarav Home Non-Stick Cookware Set',
    seller: 2,
    mrp: 3999,
    off: 55,
    gst: 18,
    hsn: '7615',
    blurb: 'PFOA-free granite non-stick set with cool-touch handles; induction and gas compatible.',
    highlights: ['PFOA-free non-stick', 'Induction ready', 'Cool-touch handles'],
    specs: [
      ['Includes', 'Kadai, tawa, frying pan, lids'],
      ['Warranty', '1 year'],
    ],
    axes: { 'pack-of': ['3', '5'] },
    bump: { 'pack-of': [0, 0.65] },
    attrs: { material: 'Non-stick' },
  },
  {
    leaf: 'cookware',
    brand: 'Cedar & Co',
    name: 'Cedar & Co Pre-Seasoned Cast Iron Kadai',
    seller: 2,
    mrp: 2199,
    off: 40,
    gst: 18,
    hsn: '7323',
    blurb: 'Naturally non-stick when seasoned, built to be passed down.',
    highlights: ['Pre-seasoned', 'Even heat retention', 'Works on all cooktops'],
    specs: [['Diameter', '26 cm']],
    attrs: { material: 'Stainless Steel' },
  },
  {
    leaf: 'home-decor',
    brand: 'Cedar & Co',
    name: 'Cedar & Co Ceramic Table Lamp',
    seller: 2,
    mrp: 1799,
    off: 45,
    gst: 18,
    hsn: '9405',
    blurb: 'A hand-glazed ceramic base with a linen shade for warm, ambient light.',
    highlights: ['Hand-glazed ceramic base', 'Linen shade', 'E27 holder (bulb not included)'],
    specs: [['Height', '42 cm']],
    axes: { color: ['White', 'Teal'] },
  },
  {
    leaf: 'home-decor',
    brand: 'Cedar & Co',
    name: 'Cedar & Co Framed Wall Art, Set of 3',
    seller: 2,
    mrp: 1299,
    off: 50,
    gst: 12,
    hsn: '4911',
    blurb: 'Botanical line prints in matte black frames, ready to hang.',
    highlights: ['Set of 3 frames', 'Matte finish', 'Hanging kit included'],
    specs: [['Frame size', '12 x 16 inch']],
  },
  {
    leaf: 'bedsheets',
    brand: 'Aarav Home',
    name: 'Aarav Home 300 TC Cotton Bedsheet Set',
    seller: 2,
    mrp: 2499,
    off: 60,
    gst: 5,
    hsn: '6302',
    blurb:
      'Crisp 300 thread-count cotton sateen with two pillow covers; gets softer with every wash.',
    highlights: ['300 TC pure cotton', 'Elastic-free flat sheet', '2 pillow covers included'],
    specs: [
      ['Thread count', '300'],
      ['Care', 'Machine wash'],
    ],
    axes: { 'bed-size': ['Double', 'Queen', 'King'], color: ['Blue', 'Grey', 'Pink'] },
    bump: { 'bed-size': [0, 0.12, 0.25] },
    attrs: { material: 'Cotton' },
  },
  {
    leaf: 'bedsheets',
    brand: 'Aarav Home',
    name: 'Aarav Home Printed Microfibre Bedsheet',
    seller: 2,
    mrp: 1599,
    off: 55,
    gst: 5,
    hsn: '6302',
    blurb: 'Soft brushed microfibre with a vibrant print that resists fading.',
    highlights: ['Brushed microfibre', 'Fade-resistant print', 'Wrinkle-free'],
    specs: [['Thread count', '180']],
    axes: { 'bed-size': ['Single', 'Double', 'King'] },
    bump: { 'bed-size': [0, 0.18, 0.4] },
    attrs: { material: 'Polyester', color: 'Blue' },
  },
  {
    leaf: 'mixer-grinders',
    brand: 'Aarav Home',
    name: 'Aarav Home Turbo Mixer Grinder',
    seller: 2,
    mrp: 5499,
    off: 45,
    gst: 18,
    hsn: '8509',
    blurb:
      'Powerful copper motor with three stainless-steel jars for chutneys, masalas and juices.',
    highlights: ['Overload protection', '3 stainless-steel jars', 'Anti-skid feet'],
    specs: [
      ['Jars', '3'],
      ['Warranty', '2 years product, 5 years motor'],
    ],
    axes: { capacity: ['500 W', '750 W', '1000 W'] },
    bump: { capacity: [0, 0.25, 0.55] },
  },
  {
    leaf: 'mixer-grinders',
    brand: 'Voltix',
    name: 'Voltix Blend Pro Juicer Mixer Grinder',
    seller: 2,
    mrp: 6999,
    off: 40,
    gst: 18,
    hsn: '8509',
    blurb: 'A juicer-mixer-grinder in one with a continuous-juicing jar.',
    highlights: ['4 jars incl. juicer', 'Pulse + 3 speeds', 'Dishwasher-safe jars'],
    specs: [['Power', '1000 W']],
    attrs: { capacity: '1000 W' },
  },
  // ───────── Beauty
  {
    leaf: 'skincare',
    brand: 'Glow Ritual',
    name: 'Glow Ritual 15% Vitamin C Face Serum, 30 ml',
    seller: 2,
    mrp: 999,
    off: 40,
    gst: 18,
    hsn: '3304',
    blurb:
      'A stable 15% vitamin C serum with ferulic acid to brighten dull skin and fade dark spots.',
    highlights: [
      '15% L-ascorbic acid',
      'Brightens in 4 weeks',
      'Dermatologically tested',
      'Fragrance-free',
    ],
    specs: [
      ['Volume', '30 ml'],
      ['Shelf life', '24 months'],
    ],
    axes: { 'pack-of': ['1', '2'] },
    bump: { 'pack-of': [0, 0.85] },
    attrs: { 'skin-type': 'All Skin Types' },
  },
  {
    leaf: 'skincare',
    brand: 'Aura Naturals',
    name: 'Aura Naturals Pure Aloe Vera Gel, 300 ml',
    seller: 2,
    mrp: 399,
    off: 25,
    gst: 18,
    hsn: '3304',
    blurb: '99% pure aloe vera gel to soothe, hydrate and calm skin after sun or shaving.',
    highlights: ['99% aloe vera', 'Non-sticky, fast absorbing', 'Paraben-free'],
    specs: [['Volume', '300 ml']],
    axes: { 'pack-of': ['1', '3'] },
    bump: { 'pack-of': [0, 1.8] },
    attrs: { 'skin-type': 'All Skin Types' },
  },
  {
    leaf: 'skincare',
    brand: 'Glow Ritual',
    name: 'Glow Ritual Invisible SPF 50 Sunscreen',
    seller: 2,
    mrp: 699,
    off: 30,
    gst: 18,
    hsn: '3304',
    blurb: 'Lightweight broad-spectrum sunscreen with no white cast — made for Indian skin tones.',
    highlights: ['SPF 50 PA++++', 'No white cast', 'Water-resistant'],
    specs: [['Volume', '50 g']],
    attrs: { 'skin-type': 'Oily' },
  },
  {
    leaf: 'haircare',
    brand: 'Aura Naturals',
    name: 'Aura Naturals Onion & Bhringraj Hair Oil',
    seller: 2,
    mrp: 549,
    off: 30,
    gst: 18,
    hsn: '3305',
    blurb: 'A cold-pressed blend of onion, bhringraj and amla for stronger, fuller-looking hair.',
    highlights: ['Cold-pressed oils', 'No mineral oil', 'Light, non-greasy feel'],
    specs: [['Volume', '200 ml']],
    axes: { 'pack-of': ['1', '2'] },
    bump: { 'pack-of': [0, 0.9] },
  },
  {
    leaf: 'haircare',
    brand: 'Glow Ritual',
    name: 'Glow Ritual Keratin Smooth Shampoo',
    seller: 2,
    mrp: 749,
    off: 35,
    gst: 18,
    hsn: '3305',
    blurb: 'Sulphate-free shampoo that tames frizz and adds shine.',
    highlights: ['Sulphate-free', 'Keratin + argan oil', 'Colour-safe'],
    specs: [['Volume', '340 ml']],
  },
  {
    leaf: 'fragrances',
    brand: 'Glow Ritual',
    name: 'Glow Ritual Oud Noir Eau de Parfum, 100 ml',
    seller: 2,
    mrp: 2499,
    off: 45,
    gst: 18,
    hsn: '3303',
    blurb: 'A deep, smoky oud softened by amber and vanilla — long-lasting evening wear.',
    highlights: [
      '8+ hours longevity',
      'Top: saffron, Heart: oud, Base: amber',
      'Travel-safe atomiser',
    ],
    specs: [
      ['Volume', '100 ml'],
      ['Concentration', 'Eau de Parfum'],
    ],
  },
  {
    leaf: 'fragrances',
    brand: 'Aura Naturals',
    name: 'Aura Naturals Jasmine Body Mist, 150 ml',
    seller: 2,
    mrp: 599,
    off: 35,
    gst: 18,
    hsn: '3303',
    blurb: 'A fresh jasmine and white-musk body mist for an all-day light fragrance.',
    highlights: ['Alcohol-light formula', 'Fresh floral notes'],
    specs: [['Volume', '150 ml']],
  },
  // ───────── Sports
  {
    leaf: 'gym-equipment',
    brand: 'PeakFit',
    name: 'PeakFit Adjustable Dumbbell Set, 20 kg',
    seller: 2,
    mrp: 5999,
    off: 45,
    gst: 18,
    hsn: '9506',
    blurb:
      'Rubber-coated adjustable dumbbells with a secure collar lock — a full home gym in one pair.',
    highlights: ['Adjustable 2.5–20 kg', 'Anti-roll hex rubber plates', 'Secure collar lock'],
    specs: [['Total weight', '20 kg (pair)']],
    axes: { color: ['Black', 'Red'] },
  },
  {
    leaf: 'gym-equipment',
    brand: 'Boltz Sports',
    name: 'Boltz Resistance Bands Set of 5',
    seller: 2,
    mrp: 999,
    off: 50,
    gst: 18,
    hsn: '9506',
    blurb: 'Five latex bands from light to extra-heavy, with door anchor, handles and carry bag.',
    highlights: ['5 resistance levels', 'Door anchor + handles', 'Carry bag included'],
    specs: [['Levels', '5']],
    axes: { color: ['Black', 'Green'] },
  },
  {
    leaf: 'yoga',
    brand: 'PeakFit',
    name: 'PeakFit Anti-Skid Yoga Mat, 6 mm',
    seller: 2,
    mrp: 1499,
    off: 60,
    gst: 18,
    hsn: '9506',
    blurb: 'Dense, cushioned and genuinely non-slip — even for sweaty hot-yoga sessions.',
    highlights: ['6 mm cushioning', 'Dual-texture grip', 'Includes carry strap'],
    specs: [['Size', '183 x 61 cm']],
    axes: { color: ['Purple', 'Teal', 'Grey'] },
  },
  {
    leaf: 'yoga',
    brand: 'PeakFit',
    name: 'PeakFit High-Density Yoga Block, Pair',
    seller: 2,
    mrp: 699,
    off: 45,
    gst: 18,
    hsn: '9506',
    blurb: 'Firm EVA blocks that support deeper, safer stretches.',
    highlights: ['High-density EVA', 'Bevelled edges'],
    specs: [['Size', '23 x 15 x 7.5 cm']],
  },
  {
    leaf: 'cricket',
    brand: 'Boltz Sports',
    name: 'Boltz Kashmir Willow Cricket Bat',
    seller: 2,
    mrp: 2999,
    off: 40,
    gst: 12,
    hsn: '9506',
    blurb:
      'Full-size Kashmir willow bat with a thick edge, ready for tape-ball and leather-ball nets.',
    highlights: ['Grade A Kashmir willow', 'Thick edges, high middle', 'Cane handle with grip'],
    specs: [
      ['Size', 'Full size (SH)'],
      ['Weight', '1.2 kg'],
    ],
  },
  {
    leaf: 'cricket',
    brand: 'Boltz Sports',
    name: 'Boltz Match Leather Cricket Balls, Pack of 3',
    seller: 2,
    mrp: 799,
    off: 30,
    gst: 12,
    hsn: '9506',
    blurb: 'Four-piece leather balls with a hand-stitched seam for consistent bounce and swing.',
    highlights: ['Four-piece leather', 'Hand-stitched seam'],
    specs: [['Pack', '3 balls']],
  },
  // ───────── Books
  {
    leaf: 'fiction-books',
    brand: 'Pageturner',
    name: 'The Monsoon Archive — A Novel',
    seller: 2,
    mrp: 499,
    off: 30,
    gst: 0,
    hsn: '4901',
    blurb:
      'A sweeping family saga across three generations in a Kerala tharavad, told through letters kept in a teak trunk.',
    highlights: ['Paperback, 384 pages', 'Language: English', 'Publisher: Pageturner Press'],
    specs: [
      ['Author', 'Meera Raghavan'],
      ['Pages', '384'],
      ['Language', 'English'],
      ['ISBN', '978-93-5000-001-1'],
    ],
    tags: ['novel', 'bestseller'],
  },
  {
    leaf: 'fiction-books',
    brand: 'Pageturner',
    name: 'Letters from Lucknow',
    seller: 2,
    mrp: 399,
    off: 25,
    gst: 0,
    hsn: '4901',
    blurb: 'A tender epistolary romance set in the lanes of old Lucknow.',
    highlights: ['Paperback, 256 pages', 'Language: English'],
    specs: [
      ['Author', 'Faiz Rahman'],
      ['Pages', '256'],
      ['Language', 'English'],
    ],
  },
  {
    leaf: 'self-help-books',
    brand: 'Pageturner',
    name: 'The Calm Compass: Habits for a Steady Mind',
    seller: 2,
    mrp: 599,
    off: 35,
    gst: 0,
    hsn: '4901',
    blurb: 'Practical, research-backed routines to stay focused and unhurried in a noisy world.',
    highlights: ['Paperback, 312 pages', 'Includes 30-day workbook'],
    specs: [
      ['Author', 'Dr. Kavita Rao'],
      ['Pages', '312'],
      ['Language', 'English'],
    ],
    tags: ['bestseller'],
  },
  {
    leaf: 'self-help-books',
    brand: 'Pageturner',
    name: 'Deep Work Diaries',
    seller: 2,
    mrp: 549,
    off: 30,
    gst: 0,
    hsn: '4901',
    blurb: 'A founder’s honest diary on building focus-first teams and protecting maker time.',
    highlights: ['Paperback, 280 pages'],
    specs: [
      ['Author', 'Siddharth Nair'],
      ['Pages', '280'],
    ],
  },
  {
    leaf: 'notebooks',
    brand: 'Pageturner',
    name: 'Pageturner A5 Hardbound Dotted Journal',
    seller: 2,
    mrp: 349,
    off: 30,
    gst: 12,
    hsn: '4820',
    blurb:
      '120 GSM ivory paper that handles fountain pens, with a ribbon bookmark and elastic closure.',
    highlights: ['120 GSM acid-free paper', '192 pages', 'Ribbon + elastic band'],
    specs: [
      ['Size', 'A5'],
      ['Ruling', 'Dotted'],
    ],
    axes: { 'pack-of': ['1', '2', '3'] },
    bump: { 'pack-of': [0, 0.9, 1.75] },
    attrs: { color: 'Black' },
  },
  {
    leaf: 'notebooks',
    brand: 'Pageturner',
    name: 'Pageturner 2027 Weekly Planner',
    seller: 2,
    mrp: 599,
    off: 40,
    gst: 12,
    hsn: '4820',
    blurb: 'A week-per-spread planner with habit tracker, goal pages and a pocket folder.',
    highlights: ['Week-per-spread layout', 'Habit tracker + goals', 'Lay-flat binding'],
    specs: [['Size', 'A5']],
  },
  // ───────── Toys & baby
  {
    leaf: 'toys',
    brand: 'LittleLark',
    name: 'LittleLark 100-Piece Wooden Building Blocks',
    seller: 2,
    mrp: 1299,
    off: 50,
    gst: 12,
    hsn: '9503',
    blurb:
      'Smooth, child-safe beechwood blocks in 12 shapes — open-ended play that builds spatial skills.',
    highlights: ['100 pieces, 12 shapes', 'Non-toxic water-based paint', 'Storage tub included'],
    specs: [
      ['Age', '3+ years'],
      ['Material', 'Beechwood'],
    ],
  },
  {
    leaf: 'toys',
    brand: 'LittleLark',
    name: 'LittleLark Remote Control Stunt Racer',
    seller: 2,
    mrp: 1999,
    off: 55,
    gst: 12,
    hsn: '9503',
    blurb:
      '2.4 GHz remote-control stunt car that flips, spins and drifts — rechargeable and rugged.',
    highlights: ['2.4 GHz remote', '360° stunt flips', 'USB rechargeable'],
    specs: [
      ['Age', '6+ years'],
      ['Battery', '500 mAh'],
    ],
  },
  {
    leaf: 'toys',
    brand: 'LittleLark',
    name: 'LittleLark Super-Soft Plush Teddy, 40 cm',
    seller: 2,
    mrp: 899,
    off: 40,
    gst: 12,
    hsn: '9503',
    blurb: 'An ultra-soft hug-ready teddy, safe for newborns and machine washable.',
    highlights: ['Hypoallergenic fibre fill', 'Machine washable', 'Embroidered eyes'],
    specs: [['Height', '40 cm']],
    axes: { color: ['Beige', 'Pink', 'Blue'] },
  },
  {
    leaf: 'baby-care',
    brand: 'LittleLark',
    name: 'LittleLark Gentle Baby Massage Oil, 200 ml',
    seller: 2,
    mrp: 349,
    off: 20,
    gst: 18,
    hsn: '3304',
    blurb: 'Almond and sesame blend that nourishes delicate skin; dermatologically tested.',
    highlights: ['Paraben & mineral oil free', 'Dermatologically tested'],
    specs: [['Volume', '200 ml']],
  },
  {
    leaf: 'baby-care',
    brand: 'LittleLark',
    name: 'LittleLark Organic Baby Wipes, Pack of 3',
    seller: 2,
    mrp: 449,
    off: 25,
    gst: 18,
    hsn: '3307',
    blurb: '99% water wipes with aloe — fragrance-free and gentle even on newborn skin.',
    highlights: ['99% water', 'Fragrance-free', '72 wipes x 3'],
    specs: [['Count', '216']],
    axes: { 'pack-of': ['1', '3'] },
    bump: { 'pack-of': [0, 1.7] },
  },
];
